### PR TITLE
Finnish translation, layout fixes, merge Statistics.qml to FirstPage.qml

### PR DESCRIPTION
**Pull request by direc85**
I added Finnish translation, fixed the start page layout a bit and renamed translations for consistency.

### CODE REVIEW

**Comment by direc85** [comment]
Wait, it does not actually translate the program in Finnish... Please don't merge yet.

**Comment by direc85** [comment]
OK, now I can use the Finnish translation on my device. I'll use it and let you know if anything weird come up. I also got rid of the jerky animations, so using the app is now more fluent experience.

I think a semi-major version bump is in place because of the .cpp rewrite... :)

Thanks!

**Comment by direc85** [comment]
I got a little carried away. I thought the buttons at the Statistics.qml page were too non-Sailfishy, so I merged the functionality to FirstPage.qml pull down and push up menus instead. In my opinion this results in fairly consistent UI - but I guess this is subjective in the end.

**Comment by direc85** [comment]
About harbour-budgetbook.cpp changes: At first I created the Finnish translation and tested in on my Sony Xperia X running Sailfish X. I noticed that I couldn't get the Finnish translation to show up, so I added lines 75-61. The app didn't compile, so I started to eliminate error messages by including necessary headers. At this point I got only white screen for whatever reason, so I started to include lines 54-55 and 62-65, after which the application started to work as expected, this time with translations.

Lines 57-61 are the actual lines in order for the translation to work, the rest is mostly dependencies in order for it to work and the file to compile in the first place. I also think that the app is much more compatible with Sailfish OS version 2 and up, now that it creates the app properly.

I hope this explains the changes.

**Comment by marmay** [comment]
Thanks, I'll do some more testing and make sure that the Swedish translation from another pull request, as well as the Czech, Dutch and Taiwanese translations from transifex also end up in the new release. Once everything works, I'll push it to harbour as 0.4.0-1, probably around next weekend.

Thanks for your contributions.

**Comment by direc85** [comment]
You're welcome!

**Pull request merged**
