### PR TITLE
Create harbour-budgetbook-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted

### CODE REVIEW

**Comment by marmay** [comment]
Just wanted to let you know that I did not forget your translations. I am going to merge it during soon. Thank you!

**Comment by eson57** [comment]
Ok... no problem.  :+1:

**Comment by suedi** [comment]
About translation

I just skimmed it but I don't know if
`tagg` is a good translation of `tag`

I would keep it as `tag`

@marmay thanks for a good app
@eson57 thanks for swe translation

**Comment by eson57** [comment]
'Tagg' is the commonly accepted translation of Tag...

http://www.datatermgruppen.se/index.php?option=com_content&view=article&id=89&Itemid=91&obj=a132&uttr=tag
https://amagama-live.translatehouse.org/
http://www.microsoft.com/language/en-us/Search.aspx?sString=tag&langID=sv-se

**Comment by suedi** [comment]
OK, then leave it, not a big problem

Hurts my eyes though.

Thanks again for translation!

**Pull request merged**
